# Generated by Django 2.2.7 on 2019-11-29 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Squirrel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Longitude', models.FloatField(help_text='Longitude')),
                ('Latitude', models.FloatField(help_text='Latitude')),
                ('Unique_Squirrel_ID', models.CharField(help_text='ID of squirrel', max_length=100)),
                ('Shift', models.CharField(choices=[('PM', 'PM'), ('AM', 'AM')], max_length=2)),
                ('Date', models.DateField(help_text='Date of squirrel')),
                ('Age', models.CharField(choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile'), ('Other', 'Other')], default='Other', help_text='Age of Squirrel', max_length=20)),
                ('Primary_Fur_Color', models.CharField(choices=[('Gray', 'Gray'), ('Cinnamon', 'Cinnamon'), ('Black', 'Black'), ('Other', 'Other')], default='Other', max_length=100)),
                ('Location', models.CharField(choices=[('Ground_Plane', 'Ground_Plane'), ('Above_Ground', 'Above_Ground'), ('Other', 'Other')], default='Other', help_text='locations of squirrel', max_length=100)),
                ('Specific_Location', models.CharField(help_text='Specific Locations of Squirrel', max_length=100)),
                ('Running', models.CharField(choices=[('True', 'True'), ('False', 'False')], help_text='Running or not', max_length=10)),
                ('Chasing', models.CharField(choices=[('True', 'True'), ('False', 'False')], help_text='Chasing or not', max_length=10)),
                ('Climbing', models.CharField(choices=[('True', 'True'), ('False', 'False')], help_text='Climb or not', max_length=5)),
                ('Eating', models.CharField(choices=[('True', 'True'), ('False', 'False')], help_text='Eat or not', max_length=5)),
                ('Foraging', models.CharField(choices=[('True', 'True'), ('False', 'False')], help_text='Forage or not', max_length=5)),
                ('Other_Activities', models.CharField(help_text='Other activities', max_length=100)),
                ('Kuks', models.CharField(choices=[('True', 'True'), ('False', 'False')], help_text='Kuks or not', max_length=5)),
                ('Quaas', models.CharField(choices=[('True', 'True'), ('False', 'False')], help_text='Quaas or not', max_length=5)),
                ('Moans', models.CharField(choices=[('True', 'True'), ('False', 'False')], help_text='Moans or not', max_length=5)),
                ('Tail_flags', models.CharField(choices=[('True', 'True'), ('False', 'False')], help_text='Tail flags or not', max_length=5)),
                ('Tail_twitches', models.CharField(choices=[('True', 'True'), ('False', 'False')], help_text='Tail twitches or not', max_length=5)),
                ('Approaches', models.CharField(choices=[('True', 'True'), ('False', 'False')], help_text='Approaches or not', max_length=5)),
                ('Indifferent', models.CharField(choices=[('True', 'True'), ('False', 'False')], help_text='Indifferent or not', max_length=5)),
                ('Runs_from', models.CharField(choices=[('True', 'True'), ('False', 'False')], help_text='Runs from or not', max_length=5)),
            ],
        ),
    ]
