# Generated by Django 2.2.7 on 2019-12-02 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('st', '0002_auto_20191202_0432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='Approaches',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Chasing',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Climbing',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Eating',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Foraging',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Indifferent',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Kuks',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Moans',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Quaas',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Running',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Runs_from',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Tail_flags',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Tail_twitches',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Unique_Squirrel_ID',
            field=models.CharField(help_text='Unique ID of squirrel', max_length=60),
        ),
    ]
