# Generated by Django 2.2.7 on 2019-11-29 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('st', '0002_auto_20191129_0501'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidences',
            name='location',
            field=models.CharField(default='abc', max_length=20),
            preserve_default=False,
        ),
    ]
